--
-- PostgreSQL database dump
--

-- Dumped from database version 12.2
-- Dumped by pg_dump version 12.2

-- Started on 2020-05-11 04:16:01

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 205 (class 1259 OID 28583)
-- Name: Actor; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Actor" (
    id integer NOT NULL,
    name character varying(20) NOT NULL,
    age integer NOT NULL,
    gender character varying(60) NOT NULL,
    city character varying(120) NOT NULL,
    state character varying(120) NOT NULL,
    phone character varying(120) NOT NULL,
    email character varying(120),
    website character varying(120)
);


ALTER TABLE public."Actor" OWNER TO postgres;

--
-- TOC entry 204 (class 1259 OID 28581)
-- Name: Actor_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public."Actor_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public."Actor_id_seq" OWNER TO postgres;

--
-- TOC entry 2849 (class 0 OID 0)
-- Dependencies: 204
-- Name: Actor_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public."Actor_id_seq" OWNED BY public."Actor".id;


--
-- TOC entry 203 (class 1259 OID 28572)
-- Name: Movie; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Movie" (
    id integer NOT NULL,
    title character varying(120) NOT NULL,
    excerpt character varying(500),
    release_date date NOT NULL
);


ALTER TABLE public."Movie" OWNER TO postgres;

--
-- TOC entry 207 (class 1259 OID 28594)
-- Name: MovieCast; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."MovieCast" (
    id integer NOT NULL,
    movie_id integer NOT NULL,
    actor_id integer NOT NULL
);


ALTER TABLE public."MovieCast" OWNER TO postgres;

--
-- TOC entry 206 (class 1259 OID 28592)
-- Name: MovieCast_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public."MovieCast_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public."MovieCast_id_seq" OWNER TO postgres;

--
-- TOC entry 2850 (class 0 OID 0)
-- Dependencies: 206
-- Name: MovieCast_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public."MovieCast_id_seq" OWNED BY public."MovieCast".id;


--
-- TOC entry 202 (class 1259 OID 28570)
-- Name: Movie_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public."Movie_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public."Movie_id_seq" OWNER TO postgres;

--
-- TOC entry 2851 (class 0 OID 0)
-- Dependencies: 202
-- Name: Movie_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public."Movie_id_seq" OWNED BY public."Movie".id;


--
-- TOC entry 2702 (class 2604 OID 28586)
-- Name: Actor id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Actor" ALTER COLUMN id SET DEFAULT nextval('public."Actor_id_seq"'::regclass);


--
-- TOC entry 2701 (class 2604 OID 28575)
-- Name: Movie id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Movie" ALTER COLUMN id SET DEFAULT nextval('public."Movie_id_seq"'::regclass);


--
-- TOC entry 2703 (class 2604 OID 28597)
-- Name: MovieCast id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."MovieCast" ALTER COLUMN id SET DEFAULT nextval('public."MovieCast_id_seq"'::regclass);


--
-- TOC entry 2841 (class 0 OID 28583)
-- Dependencies: 205
-- Data for Name: Actor; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Actor" (id, name, age, gender, city, state, phone, email, website) FROM stdin;
1	Sylvester Stallone	59	Male	Arizona	TX	123456	sylvie@gmail.com	sylvie.com
2	Sylvester Stallone	59	Male	Arizona	TX	123456	sylvie@gmail.com	sylvie.com
3	Sylvester Stallone	59	Male	Arizona	TX	123456	sylvie@gmail.com	sylvie.com
4	Sylvester Stallone	59	Male	Arizona	TX	123456	sylvie@gmail.com	sylvie.com
5	Sylvester Stallone	59	Male	Arizona	TX	123456	sylvie@gmail.com	sylvie.com
6	Sylvester Stallone	59	Male	Arizona	TX	123456	sylvie@gmail.com	sylvie.com
7	Sylvester Stallone	59	Male	Arizona	TX	123456	sylvie@gmail.com	sylvie.com
8	Sylvester Stallone	59	Male	Arizona	TX	123456	sylvie@gmail.com	sylvie.com
\.


--
-- TOC entry 2839 (class 0 OID 28572)
-- Dependencies: 203
-- Data for Name: Movie; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Movie" (id, title, excerpt, release_date) FROM stdin;
1	Dark Knight	See the famous Dark Knight in action	2020-10-08
2	Dark Knight	See the famous Dark Knight in action	2020-10-08
3	Dark Knight	See the famous Dark Knight in action	2020-10-08
4	Dark Knight	See the famous Dark Knight in action	2020-10-08
5	Dark Knight	See the famous Dark Knight in action	2020-10-08
6	Dark Knight and Joker	\N	2020-10-08
\.


--
-- TOC entry 2843 (class 0 OID 28594)
-- Dependencies: 207
-- Data for Name: MovieCast; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."MovieCast" (id, movie_id, actor_id) FROM stdin;
\.


--
-- TOC entry 2852 (class 0 OID 0)
-- Dependencies: 204
-- Name: Actor_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Actor_id_seq"', 14, true);


--
-- TOC entry 2853 (class 0 OID 0)
-- Dependencies: 206
-- Name: MovieCast_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."MovieCast_id_seq"', 6, true);


--
-- TOC entry 2854 (class 0 OID 0)
-- Dependencies: 202
-- Name: Movie_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Movie_id_seq"', 12, true);


--
-- TOC entry 2707 (class 2606 OID 28591)
-- Name: Actor Actor_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Actor"
    ADD CONSTRAINT "Actor_pkey" PRIMARY KEY (id);


--
-- TOC entry 2709 (class 2606 OID 28599)
-- Name: MovieCast MovieCast_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."MovieCast"
    ADD CONSTRAINT "MovieCast_pkey" PRIMARY KEY (id, movie_id, actor_id);


--
-- TOC entry 2705 (class 2606 OID 28580)
-- Name: Movie Movie_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Movie"
    ADD CONSTRAINT "Movie_pkey" PRIMARY KEY (id);


--
-- TOC entry 2711 (class 2606 OID 28605)
-- Name: MovieCast MovieCast_actor_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."MovieCast"
    ADD CONSTRAINT "MovieCast_actor_id_fkey" FOREIGN KEY (actor_id) REFERENCES public."Actor"(id) ON DELETE CASCADE;


--
-- TOC entry 2710 (class 2606 OID 28600)
-- Name: MovieCast MovieCast_movie_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."MovieCast"
    ADD CONSTRAINT "MovieCast_movie_id_fkey" FOREIGN KEY (movie_id) REFERENCES public."Movie"(id) ON DELETE CASCADE;


-- Completed on 2020-05-11 04:16:01

--
-- PostgreSQL database dump complete
--

