"""empty message

Revision ID: 669efd48aca9
Revises: 2dce602cdf30
Create Date: 2020-05-10 00:04:39.948733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '669efd48aca9'
down_revision = '2dce602cdf30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('MovieCast', 'releases')
    op.drop_column('MovieCast', 'releases2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('MovieCast', sa.Column('releases2', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('MovieCast', sa.Column('releases', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
